### ISSUE TITLE
Contribution 2 

### ISSUE THREAD

**Issue by MStirmel02** [mlhaus/Open-Source-2023-mon-wed#28]
I will do: [MapAB4](https://codingbat.com/prob/p136950) from map1 and[ WordAppend](https://codingbat.com/prob/p103593) from map2

**Comment by Darrial720** [comment]
I will do:
Map 1-  [mapAB2](https://codingbat.com/prob/p115011)
Map 2- [wordAppend](https://codingbat.com/prob/p103593)

**Comment by mlhaus** [comment]
👍
